### ISSUE TITLE
Tab key should insert spaces if that's the indent type

### ISSUE THREAD

**Issue by mattpass** [mattpass/ICEcoder#536]
Seems to insert tabs instead?

**Comment by andrey012** [comment]
I've fixed it in my fork, you can check commit 52d7d0819c9281f8d7f52a3443c7cb296fe04058
Actually this should be fixed in CodeMirror, because it ignores appropriate configuration setting, but CodeMirror developer rejected my fix, so I made a workaround in IceCoder. 
Also, I made indentAuto configurable, because I could not understand this feature (or it is simply not working for me).

**Comment by mattpass** [comment]
This issue has been covered so closing.
