### ISSUE TITLE
Save file improvements

### ISSUE THREAD

**Issue by mattpass** [mattpass/ICEcoder#610]
Saving can be a bit glitchy, possibly due to a variety of reasons such as lot of net connection, a glitch in sending and even ICEcoder not handling these things well. The result is that the save process appears stuck and then copying unsaved content, a reload, pasting and saving again is needed.

As well as handlng misfire events better, I am planning to speed up the save process a lot by:

* Only sending the chunks that are *different*. Let's say you have a file open with 2000 lines in it, but you only edit 3 and save. Right now it's sending the entire content of all 2000 lines. This is wasteful and slower than it needs to be. It could also be a source of hangups and misfires due to there being more content, which cause ICEcoder to stop saving. It's better to only send the added/edited/deleted content and stitch these changes into file when saved on the server. A huge time improvement would be had and maybe even vastly reduce issues caused by misfires.
* lz compress the content client and decompress server side. We're sending plaintext otherwise which has no saving on data length. A cut-off point could be implemented, as with the above enhancement there is no point spending the fraction of a second compressing and decompressing content if say just 3 characters are changed. Perhaps over 50 chararacters are lz compressed and under that are sent as plain text. As well as content sent, we'll have to identify if it's plain text or lz compressed when sending. This wasn't feasible until recently when the lz-string-php lib was fixed, so we can compress client side with JS and server side with this (fixed) lib: https://github.com/nullpunkt/lz-string-php/issues/3#issuecomment-190144411

**Comment by mattpass** [comment]
OK saving now only sends the data that has changed (insert, replace or delete) plus the line numbers and stitches those changes onto the server side file.

Result is much quicker file saves on large documents with say only minor edits, since hardly any data is sent to the server when saving.

Next step is to LZ compress the data sent and uncompress the other end. This will result in smaller data again for minor edits but less data to send when you're saving a lot of data too! :-)

**Comment by mattpass** [comment]
Note there is a reported FTP saving issue introduced in 5.3 to look into (see Google Groups post).

**Comment by mattpass** [comment]
Is now LZ compressing the data but in a Base 64 format. Asking repo owner to help with UTF-16 as the standard implementation isn't enough.

Also borrowed a users server who had the JS jamming issue which has now been resolved.

**Comment by microvb** [comment]
I am experiencing another 'js jamming' issue on save, if you wanted to investigate. It started happening immediately after the script ran to check for plugin updates and for some reason `file_get_contents` failed. The result since, has resulted in the `&file=` missing from the XHR request to the server.

While investigating the issue, I noticed some of the single apostrophes were not escaped in some of the javascript being generated (pull request incoming), however I haven't been able to locate the source of this new (yet old) issue.

**Comment by mattpass** [comment]
Thanks for the info - it started happening after you opened the plugins manager modal? Do you have PHP logs to help pinpoint the issue? Some people have reported problems with fopen and I've considered switching these around to primarily use curl rather than fopen:

```
// Now get our plugin data and put into a PHP array
if (ini_get('allow_url_fopen')) {
	$pluginsDataJS = @file_get_contents($pluginsDataSrc, false, $context);
	if (!$pluginsDataJS) {
		$pluginsDataJS = file_get_contents(str_replace("https:","http:",$pluginsDataSrc), false, $context);
	}
} elseif (function_exists('curl_init')) {
	$pDSrc = curl_init($pluginsDataSrc);
	curl_setopt($pDSrc, CURLOPT_SSL_VERIFYPEER, false);
	curl_setopt($pDSrc, CURLOPT_RETURNTRANSFER, true);
	$pluginsDataJS = curl_exec($pDSrc);
}
```

**Comment by mattpass** [comment]
@microvb - If you open lib/config___settings.php and change 'devMode' from false to true, it loads the non-minified lib/ice-coder.js instead of lib/ice-coder.min.js. We'll then be able to see the line it's having trouble with.

Thanks for all your help BTW! :+1:

**Comment by microvb** [comment]
Not a problem.  You have done fantastic work with this project.  I was also considering sending a pull request with file_get_contents() yanked and depending solely on curl, however I felt that you have it in  there for comparability reasons.  Not sure what caused file_get_contents() to fail when grabbing the plugin JSOn file from your server.  Have you considered moving it to github / cloudflare  and just using the file_get_contents / curl requests from there ?

Also, I have made a backup of the 'broken' ice and did a fresh pull without installing any plugins and it has been running beautifully so it seems there is definitely something strange happening if a plugin is installed (and after removing the plugin, the problem persisted, so 'was' installed also applies).

Just a shot in the dark as I am working on something else at the moment and need the working ice in place, if I could hazard a guess as to what the problem is, it would be something to do with the way the settings are being stored/loaded for the plugin.  I have no idea where that is stored, or if it gets cleared after uninstalling a plugin.  The specific plugin i tested with was the zip one.

Should be able to poke at this a bit later, but hoping this is enough information to go on to search and destroy this haunting pest.

**Comment by mattpass** [comment]
Yep, file_get_contents and curl are both there for compatibility reasons tho fopen and other related settings a server has, can cause issues for users. So I'd like to keep both but maybe put curl first if that's maybe more reliable/less prone to issues. I don't think it's a JSON serving/availability issue but GitHub or CDN could be an idea for the future. GitHub if anything.

Some plugins are older than others and maybe need checking over. The 'Zip It!' plugin is a bit different to the others since it zips everything up on an interval. It's probably the first plugin I wrote and has been superceded by the inbuilt backup/version control system. I'll likely end up dropping it.

Your settings are stored in a lib/config-[DOMAIN].php file or a lib/config-[NAME]-[DOMAIN].php file if you have multiUser set to true (in lib/config___settings.php). The installed plugins info is in an array, including what to run, the target and the minutes if on an interval. The array item is removed from the array on removing the plugin using the UI. Weird things were broken after installing Zip It!, must be the interval thing causing issues but shouldn't be broken after removing the plugin?

Might investigate that plus drop Zip It! as a plugin.

**Comment by mattpass** [comment]
Made a few other save improvements to help cover errors. It will now inform the user of a save issue if there's an HTTP error and not assume we can get error info from JSON returned (eg under a no permissions situation), which in turn causes a JS error which jams everything up. Also added in some extra code to detect if we already pushed an item to the serverqueue that we're requesting again. If so, it won't add it again and instead clear the item. This means it'll repetitively save as fast as it can if you hold down CTRL/Cmd+S, rather than jamming up with an unnecessary queue.

**Comment by mattpass** [comment]
LZ Compression on the JS and PHP side has been dropped because of char encoding issues that were cropping up, plus it was PHP 5.3+ and ICEcoder is 5.0+. Rather than provide glitchy support for those with 5.3+ I've removed the LZ Compression side so it works perfectly for everyone. There was very little benefit to compressing the smaller chunks of data that are now sent (instead of whole documents), so not much reason to keep it anyway.

**Comment by mattpass** [comment]
OK all done here I think and hopefully the save jamming issue you had previously @microvb is now resolved with latest commits. Feel free to check out latest version and let me know if any issues, otherwise all done and so closing. :-)
