### ISSUE TITLE
Edits appear in a different place when saved

### ISSUE THREAD

**Issue by dancramp** [mattpass/ICEcoder#637]
Very weird issue with 5.5 - when I delete a line, it shows as edited in Icecoder, but when saved and I view source, the line (or 2nd line) above is deleted. Same issue when adding code - it is actually saved in a slightly different location, maybe 1 or 2 lines above.

Basically editing any text will then insert/delete the edit in a line above where meant effectively breaking my code. Any ideas?

**Comment by mattpass** [comment]
Am not able to reproduce this. Can you reliably recreate this issue everytime?

If so can you send the file and exact steps to create this to info@icecoder.net and I can look into fixing?

**Comment by dancramp** [comment]
Thanks for the reply. On closer inspection it may well be my code or server or something. I can replicate this fairly reliably, but it's only happening in one folder/application and only to javascript files. When viewed in dev tools, there is an additional blank 1st line which does not show in 5.5 - any edits I make are therefore 1 line out. Weird thing is, if I open the file in 5.3 and save straight away, the line disappears and all then works as it should in 5.5.

I'll keep testing, but as I can't replicate this outside of 1 folder at the moment, you may want to close this and I'll raise it again if I can work out more.

Cheers.

**Comment by mattpass** [comment]
Think the issue may be within ICEcoder. There was a new saving system implemented in v5.4 and finalised in v5.5.

Previously (in v5.3 and below) whenever you made a change and saved, it would send the whole file for saving. In v5.4 and above it sends only info about what was replaced, inserted or deleted. This results in typically much faster saves as it's only sending details about what's different since the last save and not sending the whole file.

The function that 'stitches' the changes onto the existing file is in lib/file-control-xhr.php at line 105. This receives $fileLines into the array, which are all the lines in the current saved file and applies all the $changes onto it. The returned $contents are then saved as the new file, meaning a saved copy as per what you see in your browser.

However it seems to work 99.9% of the time. Something in my stitchChanges function is off by 1 under some circumstance and causing the issue.

However I haven't been able to reproduce the issue for weeks now so am unsure what the issue is. If we can reproduce reliably we can find out where the issue is here.

**Comment by mattpass** [comment]
@dancramp Have made a slight tweak which may solve the line duplication issue but also now checks what you see on screen matches the number of characters it's saving. If it doesn't, it alerts a message re this and logs info for analysis. If you can pull the latest version from GitHub and recreate your line edit issue, it should do this and provide info for us to look at and work out what's going wrong.

Please let me know if you get this warning and log file it mentions - I'd love to fix this issue but cannot recreate the problem myself.

**Comment by dancramp** [comment]
@mattpass  - I've updated and simply opened file then tried to save - attached the save error log (zipped as not accepted otherwise - let me know if this needs sending direct).

I've had a closer look and the blank line was in existence before trying to edit in 5.5 - so what you are saying fits this, it's just not showing in 5.5.

I'm happy to send over a file/s or whatever you need!

[save-error-log.zip](https://github.com/mattpass/ICEcoder/files/234426/save-error-log.zip)

**Comment by mattpass** [comment]
Thanks @dancramp but I think the issue was a red herring caused by just opening and saving. If you could open a file, make some changes, save and then it reports an error then the log file may show something interesting.

Think my quick coding was thinking there was an error saving a file that was without changes. :-)

**Comment by mattpass** [comment]
@dancramp - someone else has reported the same issue and provided me with their log file. I think I've found the issue and applied a fix (see notes: https://github.com/mattpass/ICEcoder/issues/633#issuecomment-214665461).

Could you pull the latest code from GitHub again now and let me know if it fixes the issue for you too?

**Comment by dancramp** [comment]
@mattpass - just pulled latest code and tried editing, can't save, getting this error:

ice-coder.min.js?microtime=1461669467.3011:116 POST lib/file-control-xhr.php?action=save&file…sion=0&saveType=save&charCount=11511&csrf=2c7170e7185dd4bf1c97c225be2744c1 500 (Internal Server Error)ICEcoder.serverQueue @ ice-coder.min.js?microtime=1461669467.3011:116ICEcoder.saveFile @ ice-coder.min.js?microtime=1461669467.3011:61onclick @ (index):155
ice-coder.min.js?microtime=1461669467.3011:115 ICEcoder error info for your request...
ice-coder.min.js?microtime=1461669467.3011:115 undefined

I also can't duplicate files, getting another internal server error.

**Comment by andrewklimek** [comment]
Pretty sure I'm getting the same issue

**Comment by mattpass** [comment]
OK, spent a loooong time looking at this and think I have a solution which now works perfectly all round. Please let me know if you can pull this latest version and if you have any further troubles. Considering done and closing for now tho.

**Comment by andrewklimek** [comment]
Nice!  That's fixed for me.

**Comment by fifillomx** [comment]
Hi Matt ive been using iceCoder 5.7 for just passed 10 days, i donated for 2 sites, and just today i started to get a similar error ... is saving the lines in the wrong place, sometimes over writing other lines of the CSS file in this case. Is driving me crazy :/, hope u can take a look. I love the software but as you can understand i cant use it like that 8-/.

**Comment by mattpass** [comment]
@fifillomx It seems to now only be when you save changes in a file not created by ICEcoder and were created by PC based software. Does that correct/likely?

**Comment by fifillomx** [comment]
thanks for such a quick response ! :D, it is quite possible because its a template i bought from the paralellus runway team. Are you planing to find a solution in the near future ? or do you have any idea how to solve it yet ? :)

**Comment by mattpass** [comment]
Yes, I'll look into it very soon (as I want to get that fixed for v6.0 which should be out soon). I have a Windows PC and can create a file with Notepad and then probably see the same issue.

(The difference I'd suspect is because line endings of files created on PC are typically \r\n and Linux \n, the same for Mac now, tho very old Macs were \r but that's another story!)

I think it's probably 1 line out on the start point of your changed 'chunks' (since it won't send the entire file for saving, just the chunks you changed, for data transfer efficiency).

Leave it with me, but if you're interested, it'll be something I need to tweak in the stitchChanges function in lib/file-control-xhr.php if you wanted to look in the meantime. This stitches your changed chunks into the file.

**Comment by musicmunky** [comment]
Hey Matt - did anyone ever figure out a workaround for this?  Or how to fix it?  I'm losing my mind with this one...once in a while a file will just get "off" by about 1 line and getting things back to normal sometimes involves having to blow away my ICEcoder installation and install from scratch. (which, as you can imagine, is a rather cumbersome solution) :)

**Comment by mattpass** [comment]
Hey @musicmunky - sorry to hear you're still having troubles. I can only reproduce the same thing extremely occasionally (maybe 1 in 5,000 saves) so obviously something still not right. Do you have a file you can send me - info@icecoder.net and I can reproduce the exact steps you're doing (let me know just what).

If I can reliably reproduce the issue, I can find the problem and fix it. It's something to do with line endings but unsure of exactly what circumstances.

**Comment by musicmunky** [comment]
@mattpass - If I can reproduce the error I'll send you the steps.  You're right in that it happens rarely (about 1 in 5,000 seems accurate) but when it DOES happen getting it fixed is always difficult.  
  
I absolutely realize it will be much easier for you to figure out the root cause if I can get the steps down and repeatable.  The problem is that it seems to happen at random, and I don't always notice right away - usually only when I restart my web server and realize that nothing's working do I figure out that it has struck again.  :)  
  
Just for my own future reference, I just got it working again by doing the following:  
 - Make a backup copy of the file under a different name and DONT open it in ICEcoder  
 - Create a new file with the old file name  
 - Copy the contents of the old file into a flat text document  
 - Copy the contents of that text document into the newly created file using ICEcoder  
  
  
From one developer to another, I appreciate how much effort you've put into this app, and I use it *literally* every day.  Thank you very much for your hard work!!!

**Comment by mattpass** [comment]
Yup, each time it happens I then can't quite remember what I changed. I do something similar - copy the text when I think a screwup has happened, reload ICEcoder and paste in the whole lot and save.

Reason (I think) is, that it gets confused when the file contains a mixture of Windows and Linux based line endings (\r\n and \n respectively). It's only a theory at the moment, are you on Windows or editing files originating from a Windows PC by any chance?

Awww thanks, the kudos, it's appreciated. I only built the very early versions of ICEcoder for myself and thought other people might like it so put it out there. Didn't realise it was gonna be so popular. Same here - use it every day and is pretty good. Just need to get the pesky line saving thing sorted!

**Comment by fifillomx** [comment]
sorry i have been very busy with other projects, i will look into this again later to see if i can find an accurate way to reproduce this error.

**Comment by mattpass** [comment]
No worries @fifillomx - we're just struggling to realiably reproduce it. If you can let me know?

**Comment by musicmunky** [comment]
Hmmmmm...  
Just a quick update, it looks like it happens regardless of what platform created the file - it just happened with a file that I created on my Mac, but it's happened before with files created on Linux and Windows as well.  Sadly I didn't notice with the specific file until 24 hours later because I got distracted by something else.  
...the plot thickens...

**Comment by musicmunky** [comment]
I have no idea what's going on now, but this is driving me crazy.  Tried upgrading my development server to 5.7 today (from 5.2), and not only did this issue start happening almost immediately, when I tried to revert back to 5.2 it's now doing the same thing.  The real problem is that I can't fix it this time - none of my usual tricks are working here.  It's doing it for every file, including new files created on and off the server.  I've tested it with different file types and formats as well - all of them are exhibiting this behavior.  
  
Matt - I'm getting a little desperate at this point...I've been using icecoder for all of my side projects, and at work, and now I'm afraid to touch any of the code.  Of course I'm not angry with you at all, I know it's not your fault - just weirdness with the way different systems handle line breaks and such.  Honestly just really frustrated (again, not with you, just the app), and am willing to help in any way possible at this point to see if we can figure out what the heck is going on.  
  
I can send you a link to my instance if you want to see the behavior for yourself...lol kind of at my wits end today.  Hope we can figure this out soon!!

**Comment by mattpass** [comment]
@musicmunky Sure, it'd help to see an instance with troubles or even better send a troublesome file to info@icecoder.net. If I can reproduce the issue reliably I can fix the bug quickly 😀

**Comment by musicmunky** [comment]
I've sent an email with the server info to that address, look forward to working this out!! :-D

**Comment by mattpass** [comment]
Discovered that the issue was a \n or \r line ending as the first char (ie a blank line for line 1), is seen within the textarea ICEcoder loads the content from, but doing this via JS, browsers seem to trim off 1st char if a line return, seen as whitespace. This means line 2 with text content becomes line 1, so subsequent problems when saving, it'll save to wrong line, you end up with doubles etc.

Solution is to ltrim any \r chars and then if a \n at the first char position, replace with &#13; for a carriage return. This is absolutely picked up by browsers and so the first line is a blank as you'd expect.

Thanks to all involved and especially @musicmunky for the lend of his server for a mo to put me on the right track.

Closed!!
