### ISSUE TITLE
Very strange behaviour where the keyboard seems to full lock

### ISSUE THREAD

**Issue by moudsen** [mattpass/ICEcoder#670]
Situation occurs in any HTML code. To reproduce:

- Create new tab
- Copy/paste the following text
```
	<p>Please submit the project number and hit 'Generate':</p>
	<form id="inpForm" name="inpForm" method="post" action="/importgenerator.php">
    	<input type="text" name="pid" class="inputClass" value="<?php echo htmlspecialchars($theProjectID); ?>">
		<br/>
		<input type="submit" name="btGenerate" value="Generate" class="buttonProcess" />
		<input type="submit" name="btDownload" value="Download" class="buttonProcess" ?>
	</form>
```
- Go to the line with "<input type" and try to change the name of the input.
- I am not able to change the line in question at all (no arrows, no delete/insert characters, only able to select the line and delete it)

Can you help fixing this as currently it is an annoyance to edit externally (or to _re-type_ the sentence which does allow it to be edited). Whenever going back to the originally pasted line results however in a freeze in.

**Comment by mattpass** [comment]
This sounds like a bug fixed since the v5.7 release and already in GitHub.

The line in causing the freeze I assume is the self closing tag you have here:

```
<input type="submit" name="btGenerate" value="Generate" class="buttonProcess" />
```

If you grab the latest version from GitHub it should resolve the issue for you. I'll close this issue assuming that's the problem but please reopen if not.
