### ISSUE TITLE
I can't save files due to errors

### ISSUE THREAD

**Issue by Hexeus** [mattpass/ICEcoder#704]
I am by no means a pro, I am actually trying to learn coding, so I have absolutely no idea what to do.

Here are/is my issue(s):

/_coder/lib/file-control-xhr.php?action=save&fileMDT=undefined&fileVersion=undefined&saveType=save&csrf=92fd1b36e3f3069402e2b3cfa3261c79 Failed to load resource: the server responded with a status of 403 ()
ice-coder.min.js?microtime=1496007545.0534:132 ICEcoder error info for your request...
ice-coder.min.js?microtime=1496007545.0534:132 undefined
/_coder/lib/file-control-xhr.php?action=save&fileMDT=undefined&fileVersion=undefined&saveType=saveAs&csrf=92fd1b36e3f3069402e2b3cfa3261c79 Failed to load resource: the server responded with a status of 403 ()
ice-coder.min.js:132 ICEcoder error info for your request...
ice-coder.min.js:132 undefined

**Comment by mattpass** [comment]
This may be related to your other issue (issue #705). A 403 error would be something you need to investigate on your server as it's forbidden for some reason. Maybe a permissions issue, I'm unsure as everyones server and setup is different.

ICEcoder uses PHP for all it's file handling and so your PHP logs may turn up the error or at least help point you in the right direction. Try the same action again and watch for new error logs on your server to likely reveal the answer.

**Comment by kurtobando** [comment]
Hello, I have the same behavior on my Centos 7 VPS. It appears this behavior was caused by mod_security whenever I save my edited files. 
Here is the error logs below:

`[file "/usr/local/apache/modsecurity-cwaf/rules/08_XSS_XSS.conf"] [line "176"] [id "212590"] [rev "2"] [msg "COMODO WAF: Cross-site Scripting (XSS) Attack||icecoder.mydomain.com|F|2"] [data "Matched Data: @import found within ARGS:changes: [[\\x22equal\\x22,0,10,0,10],[\\x22insert\\x22,10,10,10,12,\\x22@import '__phones';\\x5cn\\x5cn\\x22],[\\x22equal\\x22,10,14,12,16]]"] [severity "CRITICAL"] [tag "CWAF"] [tag "XSS"] [hostname "icecoder.mydomain.com"] [uri "/lib/file-control-xhr.php"] [unique_id "W5hEJBPDHyTXkHVJFZRqqgAAAIo"], referer: https://icecoder.mydomain.com/`

I have disabled the mode_security temporary whenever I made any changes. I hope this will help you in some way.
