### ISSUE TITLE
Saving Issue (Bug?)

### ISSUE THREAD

**Issue by Hexeus** [mattpass/ICEcoder#705]
I noticed if you have the following code, it will REFUSE to save:
```
<!DOCTYPE html>
<html>

    <head>
        <meta charset="UTF-8">
        <title>Poop</title>
    </head>

    <body>

        <nav>
        </nav>

        <header>
        </header>

		<section>
		</section>


        <main>
        </main>

        <footer>
        </footer>

    </body>

</html>
```

For it to save, you are forced to put section in div tags like so:

div
section
/section
/div
```
<!DOCTYPE html>
<html>

    <head>
        <meta charset="UTF-8">
        <title>Poop</title>
    </head>

    <body>

        <nav>
        </nav>

        <header>
        </header>

		<section>
		</section>


        <main>
        </main>

        <footer>
        </footer>

    </body>

</html>
```

**Comment by mattpass** [comment]
I can save this just fine (PS - updated your example as you need triple backslashes to denote code examples).

Think this is because you have a tag there without without an end tag - ```<meta charset="UTF-8">```. What you have is absolutely right, but ICEcoder had an issue in v6.0 beta official release re self closing tags causing JS errors, which then means it can't save.

Maybe you can confirm this by opening your dev tools, go to the console tag and try to save this file? There is likely a JS error.

There has been a fix for this in this git repo since v6.0 beta release, so if you git pull the latest version it should fix this issue. I'll close assuming it does, but if not, please reopen with any more info.
