### ISSUE TITLE
Minimap - All Squashed Up - Linux Client 

### ISSUE THREAD

**Issue by marcoczen** [mattpass/ICEcoder#717]
Anyone know how to resolve this ?
![minimap-squeezed](https://user-images.githubusercontent.com/20210990/28835885-820ae8d4-7719-11e7-9df3-6dcbc2f179d8.png)

Note - its fine from a Windows 7 box.
This is a Linux/openSuse box with a nvidia card;
0f:00.0 VGA compatible controller [0300]: NVIDIA Corporation Device [10de:128b] (rev a1)
	Subsystem: ZOTAC International (MCO) Ltd. Device [19da:7326]
	Kernel driver in use: nvidia

Note - youtube, movies , flash etc plays fine on this box.

**Comment by mattpass** [comment]
Which browser is this? It'd be JavaScript that's unable to set the font size to something smaller (ie, 1-2px high) and simply not doing it. No JS errors in console?

**Comment by marcoczen** [comment]
Matt,

Chromium v52.x

When i look at he minimap - via inspect, i can see font size is 2px ?

<span style="font-size: 2px; font-family: monospace" class="cm-meta">&lt;?php</span>

**Comment by mattpass** [comment]
Hmmm, that's really not displaying at the right size then? Would be up the browser to display at 2px! CSS syntax there is fine. Only thing I could suggest is that you try changing that inline CSS to 
```
font-size: 2px !important
```
...and see if that makes a difference. Otherwise, not sure what to suggest, we're specifying we want it to be 2px high?

**Comment by marcoczen** [comment]
Hi, where is that inline css ? Which is the php file ?

**Comment by mattpass** [comment]
It's in lib/ice-coder.js lines 1220 & 1221:

https://github.com/mattpass/ICEcoder/blob/85e441390c5d59b5d9e11a66f5defdd752196a71/lib/ice-coder.js#L1220-L1221

To make use of this file, you need to open lib/config___settings.php and set devMode from false to true. Now ICEcoder will use lib/ice-coder.js rather than the minified lib/ice-coder.min.js

You can try altering 2px to something else or maybe 2px !important to see if that makes a difference?

**Comment by marcoczen** [comment]
Will try and revert.

**Comment by marcoczen** [comment]
Update  ( On Windows Box  ) - Note the minimap was NOT squashed up here. Using 
          font-size: 2px !important;
created a smaller /tinier minimap but overall no squashed up effects were observed.

Will test on the Linux Box and revert.

**Comment by marcoczen** [comment]
Update  ( On Linux Box  ) -  the problem STILL persists. minimap is still squashed .

**Comment by mattpass** [comment]
It won't have anything to do with the server it's running on but the browser you're using to view it.

I have the latest Chrome (59.0.3071.115) - so maybe Chrome needs to update?

**Comment by marcoczen** [comment]
Ok , let me see if it happens when i use FIrefox on the Linux Box.

**Comment by marcoczen** [comment]
Firefox (v51.x ) on the Linux Box - Minimap is NOT squashed. Cant remember  what it was earlier though as i stopped using Firefox after the multiple lines appearing issue.

Google-Chrome-Stable ( Version 60.0.3112.90 (Official Build) (64-bit) ) - Minimap IS OK.

Thanks Matt.

Must set set devMode to false again right ?

**Comment by mattpass** [comment]
So must be older versions of Chrome not wanting to display text at incredibly small sizes such as 2px - maybe?

Yes, if you change devMode from true to false, it will use the minified lib/ice-coder.min.js instead of lib/ice-coder.js

**Comment by marcoczen** [comment]
Thanks Matt.
